name: Auto Tweet Bot
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install tweepy
          pip install openai
      - name: Run bot
        env:
          TW_API_KEY: ${{ secrets.TW_API_KEY }}
          TW_API_SECRET: ${{ secrets.TW_API_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot.py
